# docker-compose.yml
#
# Этот файл Docker Compose определяет и конфигурирует многоконтейнерное Docker-приложение.
# Он включает сервисы для FastAPI приложения и Redis базы данных, а также управляет
# их сборкой, сетями и персистентностью данных.


services:
  # Сервис для FastAPI приложения.
  app:
    # Инструкции по сборке образа для этого сервиса.
    build:
      context: .        # Контекст сборки - текущая директория (корень проекта)
      dockerfile: Dockerfile # Имя Dockerfile для сборки
    ports:
      - "8000:8000"   # Маппинг портов: 8000 хоста -> 8000 контейнера
    env_file:
      - .env            # Загрузка переменных окружения из файла .env
    volumes:
      # Монтирование тома для персистентного хранения SQLite базы данных.
      # Данные будут сохраняться в папке 'data' в корне проекта на хосте.
      - ./data:/app/data
    # Указывает, что сервис 'app' зависит от 'redis_db'.
    # Docker Compose будет запускать 'redis_db' перед 'app'.
    depends_on:
      - redis_db

  # Сервис для Redis базы данных.
  redis_db:
    image: redis:7-alpine # Используем официальный образ Redis (облегченная версия)
    ports:
      - "6379:6379"   # Маппинг портов: 6379 хоста -> 6379 контейнера
    volumes:
      # Монтирование именованного тома для персистентного хранения данных Redis.
      - redis_data:/data

# Определение именованных томов, используемых в проекте.
# 'redis_data' используется для хранения данных Redis.
volumes:
  redis_data:
